// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tnjafhmabvkanemlnlwk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRuamFmaG1hYnZrYW5lbWxubHdrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU2MTkxMzYsImV4cCI6MjA3MTE5NTEzNn0.anYH8blyxxxlUQ-9FiS7aco40rKzoUvBrrIvuC7PGZo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});